//! Postgres-backed tests. They run only when `DATABASE_URL` is set; each test works
//! in its own freshly created schema (via `search_path`) and drops it afterwards.
//!
//! ```sh
//! DATABASE_URL=postgres://postgres:dev@localhost:55432/postgres \
//!   cargo test -p meili-ingest-control-plane --test db
//! ```

use std::str::FromStr;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use chrono::Utc;
use http_body_util::BodyExt;
use meili_ingest_control_plane::builtin_pipelines::builtin_plugin_names;
use meili_ingest_control_plane::error::ErrorBody;
use meili_ingest_control_plane::jobs::{JobRecord, JobUpdate};
use meili_ingest_control_plane::pipelines::PipelineRepo;
use meili_ingest_control_plane::resolver::ResolveResponse;
use meili_ingest_control_plane::{AppState, app, db};
use meili_ingest_plugin_sdk::{
    InputKind, JobStatus, OutputKind, PipelineDefinition, PipelineTrigger, PluginKind,
    PluginManifest, StepDefinition,
};
use serde::de::DeserializeOwned;
use sqlx::postgres::{PgConnectOptions, PgPoolOptions};
use sqlx::{AssertSqlSafe, PgPool};
use tower::ServiceExt;
use uuid::Uuid;

/// A pool whose connections all use a private schema, plus the schema name.
struct TestDb {
    pool: PgPool,
    schema: String,
    admin: PgPool,
}

impl TestDb {
    async fn drop_schema(self) {
        self.pool.close().await;
        // Schema names are generated by this test file (uuid-based), never user input.
        let _ = sqlx::query(AssertSqlSafe(format!(
            "DROP SCHEMA IF EXISTS {} CASCADE",
            self.schema
        )))
        .execute(&self.admin)
        .await;
        self.admin.close().await;
    }
}

/// `None` (after printing "skipping") when `DATABASE_URL` is unset.
async fn setup() -> Option<TestDb> {
    let Ok(url) = std::env::var("DATABASE_URL") else {
        eprintln!("skipping: DATABASE_URL not set");
        return None;
    };
    let schema = format!("cp_test_{}", Uuid::new_v4().simple());
    let admin = PgPoolOptions::new()
        .max_connections(1)
        .connect(&url)
        .await
        .unwrap();
    sqlx::query(AssertSqlSafe(format!("CREATE SCHEMA {schema}")))
        .execute(&admin)
        .await
        .unwrap();
    let opts = PgConnectOptions::from_str(&url)
        .unwrap()
        .options([("search_path", schema.as_str())]);
    let pool = PgPoolOptions::new()
        .max_connections(4)
        .connect_with(opts)
        .await
        .unwrap();
    db::migrate(&pool).await.unwrap();
    Some(TestDb {
        pool,
        schema,
        admin,
    })
}

async fn call(app: Router, req: Request<Body>) -> (StatusCode, Vec<u8>) {
    let res = app.oneshot(req).await.unwrap();
    let status = res.status();
    let bytes = res.into_body().collect().await.unwrap().to_bytes().to_vec();
    (status, bytes)
}

fn json<T: DeserializeOwned>(bytes: &[u8]) -> T {
    serde_json::from_slice(bytes).unwrap_or_else(|e| {
        panic!(
            "invalid JSON body {:?}: {e}",
            String::from_utf8_lossy(bytes)
        )
    })
}

fn req_json(method: &str, uri: &str, body: &impl serde::Serialize) -> Request<Body> {
    Request::builder()
        .method(method)
        .uri(uri)
        .header(header::CONTENT_TYPE, "application/json")
        .body(Body::from(serde_json::to_vec(body).unwrap()))
        .unwrap()
}

fn get(uri: &str) -> Request<Body> {
    Request::get(uri).body(Body::empty()).unwrap()
}

fn pdf_pipeline(uid: &str, project_id: Option<&str>) -> PipelineDefinition {
    PipelineDefinition {
        uid: uid.into(),
        name: format!("{uid} name"),
        description: Some("desc".into()),
        version: 1,
        trigger: Some(PipelineTrigger {
            content_types: vec!["application/pdf".into()],
            filename_pattern: None,
            index_pattern: Some(format!("{uid}-idx")),
        }),
        steps: vec![
            StepDefinition::new("extract", "pdf_extractor"),
            StepDefinition::new("index", "meili_indexer"),
        ],
        builtin: false,
        project_id: project_id.map(str::to_owned),
    }
}

#[tokio::test]
async fn migrations_are_idempotent_and_health_is_ok() {
    let Some(t) = setup().await else { return };
    db::migrate(&t.pool).await.unwrap();
    let (status, body) = call(app(AppState::new(t.pool.clone())), get("/health")).await;
    assert_eq!(status, StatusCode::OK);
    let v: serde_json::Value = json(&body);
    assert_eq!(v["status"], "ok");
    t.drop_schema().await;
}

#[tokio::test]
async fn pipeline_repo_crud_with_tenant_scoping() {
    let Some(t) = setup().await else { return };
    let repo = PipelineRepo::new(t.pool.clone());

    // Create global, then the same uid for a tenant.
    let global = repo.upsert(&pdf_pipeline("shared", None)).await.unwrap();
    assert_eq!(global.version, 1);
    assert_eq!(global.project_id, None);
    assert!(!global.builtin);
    let tenant = repo
        .upsert(&pdf_pipeline("shared", Some("t1")))
        .await
        .unwrap();
    assert_eq!(tenant.project_id.as_deref(), Some("t1"));

    // Update bumps version.
    let mut v2 = pdf_pipeline("shared", None);
    v2.description = Some("changed".into());
    let updated = repo.upsert(&v2).await.unwrap();
    assert_eq!(updated.version, 2);
    assert_eq!(updated.description.as_deref(), Some("changed"));
    let again = repo.upsert(&v2).await.unwrap();
    assert_eq!(again.version, 3);

    // get: tenant row first, then global.
    let got = repo.get("shared", Some("t1")).await.unwrap().unwrap();
    assert_eq!(got.project_id.as_deref(), Some("t1"));
    assert_eq!(got.version, 1);
    let got = repo.get("shared", Some("t2")).await.unwrap().unwrap();
    assert_eq!(got.project_id, None);
    assert_eq!(got.version, 3);
    let got = repo.get("shared", None).await.unwrap().unwrap();
    assert_eq!(got.project_id, None);
    assert!(repo.get("missing", None).await.unwrap().is_none());

    // list: tenant rows first, then global; other tenants excluded.
    repo.upsert(&pdf_pipeline("other", Some("t2")))
        .await
        .unwrap();
    let list = repo.list(Some("t1")).await.unwrap();
    let ids: Vec<(String, Option<String>)> = list
        .iter()
        .map(|p| (p.uid.clone(), p.project_id.clone()))
        .collect();
    assert_eq!(
        ids,
        vec![
            ("shared".to_string(), Some("t1".to_string())),
            ("shared".to_string(), None)
        ]
    );
    assert_eq!(repo.list(None).await.unwrap().len(), 1);
    assert_eq!(repo.list_all().await.unwrap().len(), 3);

    // delete is scoped.
    assert!(!repo.delete("shared", Some("nope")).await.unwrap());
    assert!(repo.delete("shared", Some("t1")).await.unwrap());
    assert!(
        repo.get("shared", Some("t1"))
            .await
            .unwrap()
            .unwrap()
            .project_id
            .is_none()
    );
    assert!(repo.delete("shared", None).await.unwrap());
    assert!(repo.get("shared", None).await.unwrap().is_none());

    t.drop_schema().await;
}

#[tokio::test]
async fn pipeline_routes_end_to_end() {
    let Some(t) = setup().await else { return };
    let state = AppState::new(t.pool.clone());

    // Create via header scope.
    let def = pdf_pipeline("hdr-scoped", None);
    let req = Request::post("/pipelines")
        .header(header::CONTENT_TYPE, "application/json")
        .header("X-Meili-Project-Id", "t1")
        .body(Body::from(serde_json::to_vec(&def).unwrap()))
        .unwrap();
    let (status, body) = call(app(state.clone()), req).await;
    assert_eq!(
        status,
        StatusCode::CREATED,
        "{}",
        String::from_utf8_lossy(&body)
    );
    let stored: PipelineDefinition = json(&body);
    assert_eq!(stored.project_id.as_deref(), Some("t1"));
    assert_eq!(stored.version, 1);
    assert_eq!(stored.steps[1].depends_on, vec!["extract"]);

    // Re-post bumps version (201 again).
    let (status, body) = call(app(state.clone()), req_json("POST", "/pipelines", &stored)).await;
    assert_eq!(status, StatusCode::CREATED);
    let stored2: PipelineDefinition = json(&body);
    assert_eq!(stored2.version, 2);

    // Unknown plugin → 422 unknown_plugin.
    let mut bad = pdf_pipeline("bad-plugin", None);
    bad.steps[0].plugin = "custom_thing".into();
    let (status, body) = call(app(state.clone()), req_json("POST", "/pipelines", &bad)).await;
    assert_eq!(status, StatusCode::UNPROCESSABLE_ENTITY);
    let err: ErrorBody = json(&body);
    assert_eq!(err.code, "unknown_plugin");
    assert!(err.error.contains("custom_thing"), "{}", err.error);

    // Register the plugin, then it is accepted.
    let manifests = vec![
        PluginManifest::new("custom_thing", "1.2.3")
            .kind(PluginKind::Grpc)
            .accepts([InputKind::Bytes])
            .produces(OutputKind::Documents),
    ];
    let (status, _) = call(
        app(state.clone()),
        req_json("POST", "/internal/plugins", &manifests),
    )
    .await;
    assert_eq!(status, StatusCode::NO_CONTENT);
    let (status, _) = call(app(state.clone()), req_json("POST", "/pipelines", &bad)).await;
    assert_eq!(status, StatusCode::CREATED);

    // GET list: the two user rows first, then every built-in. Counted from
    // `builtin_pipelines()` rather than hardcoded: the literal that used to live
    // here went stale the moment parquet/avro/msgpack were added.
    let (status, body) = call(app(state.clone()), get("/pipelines?project_id=t1")).await;
    assert_eq!(status, StatusCode::OK);
    let list: Vec<PipelineDefinition> = json(&body);
    assert_eq!(list[0].uid, "hdr-scoped");
    assert_eq!(list[1].uid, "bad-plugin");
    assert_eq!(
        list.len(),
        2 + meili_ingest_router::builtin_pipelines().len()
    );
    assert!(list[2..].iter().all(|p| p.builtin));

    // GET one (scoped) / 404 for other tenant / builtin fallback.
    let (status, body) = call(
        app(state.clone()),
        get("/pipelines/hdr-scoped?project_id=t1"),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    let one: PipelineDefinition = json(&body);
    assert_eq!(one.version, 2);
    let (status, _) = call(
        app(state.clone()),
        get("/pipelines/hdr-scoped?project_id=t2"),
    )
    .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    let (status, _) = call(app(state.clone()), get("/pipelines/builtin.html")).await;
    assert_eq!(status, StatusCode::OK);

    // Resolve for t1 → its tenant pipeline + index pattern; for t2 → the global user
    // pipeline ("bad-plugin", also triggered on application/pdf) beats the builtin.
    let (status, body) = call(
        app(state.clone()),
        req_json(
            "POST",
            "/internal/resolve",
            &serde_json::json!({"mime": "application/pdf", "project_id": "t1"}),
        ),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    let res: ResolveResponse = json(&body);
    assert_eq!(res.pipeline.uid, "hdr-scoped");
    assert_eq!(res.index_pattern.as_deref(), Some("hdr-scoped-idx"));
    let (status, body) = call(
        app(state.clone()),
        req_json(
            "POST",
            "/internal/resolve",
            &serde_json::json!({"mime": "application/pdf", "project_id": "t2"}),
        ),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    let res: ResolveResponse = json(&body);
    assert_eq!(res.pipeline.uid, "bad-plugin");
    assert_eq!(res.index_pattern.as_deref(), Some("bad-plugin-idx"));

    // Delete: wrong scope 404, right scope 204, then t1 falls back to the global user
    // pipeline (cache invalidated), and once that is gone too → builtin.
    let req = Request::delete("/pipelines/hdr-scoped")
        .body(Body::empty())
        .unwrap();
    let (status, _) = call(app(state.clone()), req).await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    let req = Request::delete("/pipelines/hdr-scoped?project_id=t1")
        .body(Body::empty())
        .unwrap();
    let (status, body) = call(app(state.clone()), req).await;
    // 200 with the sources the delete archived, so the gateway can drop their
    // Temporal schedules. None feed this pipeline.
    assert_eq!(status, StatusCode::OK);
    assert_eq!(
        json::<serde_json::Value>(&body),
        serde_json::json!({ "archived_sources": [] })
    );
    let (status, body) = call(
        app(state.clone()),
        req_json(
            "POST",
            "/internal/resolve",
            &serde_json::json!({"mime": "application/pdf", "project_id": "t1"}),
        ),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    let res: ResolveResponse = json(&body);
    assert_eq!(res.pipeline.uid, "bad-plugin");

    let req = Request::delete("/pipelines/bad-plugin")
        .body(Body::empty())
        .unwrap();
    let (status, _) = call(app(state.clone()), req).await;
    assert_eq!(status, StatusCode::OK);
    let (status, body) = call(
        app(state.clone()),
        req_json(
            "POST",
            "/internal/resolve",
            &serde_json::json!({"mime": "application/pdf", "project_id": "t1"}),
        ),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    let res: ResolveResponse = json(&body);
    assert_eq!(res.pipeline.uid, "builtin.pdf");

    t.drop_schema().await;
}

#[tokio::test]
async fn plugins_registry_falls_back_to_static_list() {
    let Some(t) = setup().await else { return };
    let state = AppState::new(t.pool.clone());

    let (status, body) = call(app(state.clone()), get("/plugins")).await;
    assert_eq!(status, StatusCode::OK);
    let list: Vec<PluginManifest> = json(&body);
    // Same reasoning as the pipeline count above: derive it, do not hardcode it.
    assert_eq!(list.len(), builtin_plugin_names().len());
    assert!(
        list.iter()
            .any(|m| m.name == "pdf_extractor" && m.kind == PluginKind::Builtin)
    );

    let manifests = vec![
        PluginManifest::new("zeta", "1.0.0").description("z"),
        PluginManifest::new("alpha", "1.0.0").description("a"),
    ];
    let (status, _) = call(
        app(state.clone()),
        req_json("POST", "/internal/plugins", &manifests),
    )
    .await;
    assert_eq!(status, StatusCode::NO_CONTENT);
    // Upsert updates in place.
    let manifests2 = vec![PluginManifest::new("alpha", "2.0.0").description("a2")];
    let (status, _) = call(
        app(state.clone()),
        req_json("POST", "/internal/plugins", &manifests2),
    )
    .await;
    assert_eq!(status, StatusCode::NO_CONTENT);

    let (status, body) = call(app(state.clone()), get("/plugins")).await;
    assert_eq!(status, StatusCode::OK);
    let list: Vec<PluginManifest> = json(&body);
    let names: Vec<&str> = list.iter().map(|m| m.name.as_str()).collect();
    assert_eq!(names, ["alpha", "zeta"]);
    assert_eq!(list[0].version, "2.0.0");

    t.drop_schema().await;
}

#[tokio::test]
async fn jobs_insert_patch_get() {
    let Some(t) = setup().await else { return };
    let state = AppState::new(t.pool.clone());
    let id = Uuid::new_v4();
    let now = Utc::now();
    let job = JobRecord {
        job_id: id,
        workflow_id: format!("ingest-{id}"),
        pipeline_uid: "builtin.pdf".into(),
        project_id: Some("t1".into()),
        index_name: Some("documents".into()),
        status: JobStatus::Queued,
        current_step: None,
        error: None,
        started_at: now,
        updated_at: now,
    };

    let (status, body) = call(app(state.clone()), req_json("POST", "/internal/jobs", &job)).await;
    assert_eq!(
        status,
        StatusCode::CREATED,
        "{}",
        String::from_utf8_lossy(&body)
    );
    let stored: JobRecord = json(&body);
    assert_eq!(stored.job_id, id);
    assert_eq!(stored.status, JobStatus::Queued);
    assert_eq!(stored.project_id.as_deref(), Some("t1"));

    let upd = JobUpdate {
        status: Some(JobStatus::Running),
        current_step: Some("extract".into()),
        ..JobUpdate::default()
    };
    let (status, body) = call(
        app(state.clone()),
        req_json("PATCH", &format!("/internal/jobs/{id}"), &upd),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    let patched: JobRecord = json(&body);
    assert_eq!(patched.status, JobStatus::Running);
    // A failed job keeps the step it stopped on: that is the diagnostic.
    assert_eq!(patched.current_step.as_deref(), Some("extract"));
    assert_eq!(patched.index_name.as_deref(), Some("documents"));
    assert!(patched.updated_at >= stored.updated_at);

    let upd = JobUpdate {
        status: Some(JobStatus::Failed),
        error: Some("boom".into()),
        ..JobUpdate::default()
    };
    let (status, body) = call(
        app(state.clone()),
        req_json("PATCH", &format!("/internal/jobs/{id}"), &upd),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    let patched: JobRecord = json(&body);
    assert_eq!(patched.status, JobStatus::Failed);
    assert_eq!(patched.error.as_deref(), Some("boom"));
    // A failed job keeps the step it stopped on: that is the diagnostic.
    assert_eq!(patched.current_step.as_deref(), Some("extract"));

    let (status, body) = call(app(state.clone()), get(&format!("/internal/jobs/{id}"))).await;
    assert_eq!(status, StatusCode::OK);
    let fetched: JobRecord = json(&body);
    assert_eq!(fetched, patched);

    let missing = Uuid::new_v4();
    let (status, body) = call(
        app(state.clone()),
        get(&format!("/internal/jobs/{missing}")),
    )
    .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    let err: ErrorBody = json(&body);
    assert_eq!(err.code, "not_found");
    let (status, _) = call(
        app(state.clone()),
        req_json(
            "PATCH",
            &format!("/internal/jobs/{missing}"),
            &JobUpdate::default(),
        ),
    )
    .await;
    assert_eq!(status, StatusCode::NOT_FOUND);

    t.drop_schema().await;
}

#[tokio::test]
async fn terminal_status_clears_the_current_step() {
    // A job that succeeded is not "on" a step. The worker patches the terminal status
    // without naming one, so this has to hold server-side or the last running value
    // sticks and the job list reads "succeeded, extract". A failed job is different:
    // it keeps the step it stopped on, asserted in jobs_insert_patch_get.
    let Some(t) = setup().await else { return };
    let state = AppState::new(t.pool.clone());
    let id = Uuid::new_v4();
    let now = Utc::now();
    let job = JobRecord {
        job_id: id,
        workflow_id: format!("ingest-{id}"),
        pipeline_uid: "builtin.pdf".into(),
        project_id: None,
        index_name: Some("documents".into()),
        status: JobStatus::Queued,
        current_step: None,
        error: None,
        started_at: now,
        updated_at: now,
    };
    let (status, _) = call(app(state.clone()), req_json("POST", "/internal/jobs", &job)).await;
    assert_eq!(status, StatusCode::CREATED);

    let running = JobUpdate {
        status: Some(JobStatus::Running),
        current_step: Some("extract".into()),
        ..JobUpdate::default()
    };
    let (_, body) = call(
        app(state.clone()),
        req_json("PATCH", &format!("/internal/jobs/{id}"), &running),
    )
    .await;
    let stored: JobRecord = json(&body);
    assert_eq!(stored.current_step.as_deref(), Some("extract"));

    let done = JobUpdate {
        status: Some(JobStatus::Succeeded),
        ..JobUpdate::default()
    };
    let (_, body) = call(
        app(state.clone()),
        req_json("PATCH", &format!("/internal/jobs/{id}"), &done),
    )
    .await;
    let stored: JobRecord = json(&body);
    assert_eq!(stored.status, JobStatus::Succeeded);
    assert_eq!(
        stored.current_step, None,
        "a finished job must not keep a current step"
    );

    t.drop_schema().await;
}
